name: Build and Release

on:
  push:
    tags:
      - 'v*'
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run \
            --rm \
            --privileged \
            -e CGO_ENABLED=1 \
            -e GITHUB_TOKEN \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}:/go/src/github.com/servprotocolorg/serv \
            -w /go/src/github.com/servprotocolorg/serv \
            ghcr.io/goreleaser/goreleaser-cross:v1.20 \
            release --rm-dist